#!/usr/bin/perl -w
#
# Nagios Addon: service checks based on host status
#Copyright (C) 2014 Stephan Callsen
#
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
#associated documentation files (the "Software"), to deal in the Software without restriction,
#including without limitation the rights to use, copy, modify, merge, publish, distribute,
#sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all copies or substantial
#portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
#LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
#WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#  Autor: Stephan Callsen
#  Date:  March. 20th 2014
#  Email: info@callsen.org
#  Version: 1.1
#
#Debian require package libnagios-object-perl
#

use Getopt::Long;
use Nagios::Config;

#my $n_hostname = $ENV{NAGIOS_HOSTNAME}
#my $n_hoststatid = $ENV{NAGIOS_HOSTSTATUSID}

my $n_hostname;
my $n_hoststatid;
my $n_lastservicestatusid;

my $nagioslivechk = '/var/lib/nagios3/rw/live';
my $nagioscmd     = '/var/lib/nagios3/rw/nagios.cmd';
my $nagiosconf    = '/etc/nagios3/nagios.cfg';

my $ext_cmd_ehsn = "ENABLE_HOST_SVC_NOTIFICATIONS";
my $ext_cmd_ehsc = "ENABLE_HOST_SVC_CHECKS";
my $ext_cmd_dhsc = "DISABLE_HOST_SVC_CHECKS";
my $ext_cmd_dhsn = "DISABLE_HOST_SVC_NOTIFICATIONS";
my $ext_cmd_pscr = "PROCESS_SERVICE_CHECK_RESULT";

my $sendcmd;
my $h_service;
#Exit on no services!
my @services = ();

my $now = `date +%s`;
chomp ($now);

GetOptions(     "h|host=s"     		=> \$n_hostname,
		"s|hoststatid=s"     	=> \$n_hoststatid,
		"l|lastservicestat=s" 	=> \$n_lastservicestatusid,
		"m|method=s"		=> \$n_method
        	#"h|help"       	=> \$HELP
);

#Get all host services either by checklive or by cpan module nagios::config
if ( defined ($n_method) && defined ($n_hostname) && defined ($n_hoststatid) && defined ($n_lastservicestatusid)) {
  if ($n_method eq "m") {
    @services = `echo \"GET services\\nColumns\: description\\nFilter\: host_name \>= $n_hostname \\n\" \| unixcat $nagioslivechk`;
  }
  else {
    my $PARS = Nagios::Config->new(Filename => $nagiosconf, Version => 2);
    my $host = $PARS->find_object($n_hostname,'Nagios::Host');
    if ( defined $host ) {
      my $servnum = 0;
      foreach my $Service ( $host->list_services ) {
        #printf "CONFIG: %s\n", $Service->{'service_description'};
        $services[$servnum] = $Service->{'service_description'};
        $servnum++;
      }
    }
  else { exit 1; }
  }
}
else { exit 1; }

#Exit on no services!
$servnum = @services;
if (!$servnum) { exit 1;}

#Send command to pipe
sub sendcommand {
  my ($command )  = @_;
  chomp ( $command );
  if ( defined ( $command ) ) { print CMD "\[$now\] $command\n"; }
}

open CMD, ">$nagioscmd" or die $!;

#Enable all services for a host
if (!$n_hoststatid) {
  foreach $h_service (@services) {
    chomp ($h_service);
    #printf ("Activate-$h_service\n");
    sendcommand "$ext_cmd_pscr;$n_hostname;$h_service;$n_lastservicestatusid;OK";
  }
  sendcommand "$ext_cmd_ehsn;$n_hostname";
  sendcommand "$ext_cmd_ehsc;$n_hostname";
}
#Disable all services for a host
else {
   sendcommand "$ext_cmd_dhsc;$n_hostname";
   sendcommand "$ext_cmd_dhsn;$n_hostname";
   foreach $h_service (@services) {
     chomp ($h_service);
     #printf ("Deactivate-$h_service\n");
     sendcommand "$ext_cmd_pscr;$n_hostname;$h_service;3;Process has stopped by host problem";
  }
}

close CMD;
exit 0;
